urbanopt/geojson-modelica-translator

geojson_modelica_translator/model_connectors/templates/spawn_fmu.mot

This closes #8 
It also includes the removal of `ReaderTMY3` instance in `spawn_fmu.mot` as it is not used by EnergyPlus FMU.
With those updates each exported Spawn model can be simulated with JModelica.

Issue8 spawn integration

---

geojson_modelica_translator/model_connectors/teaser.py
geojson_modelica_translator/modelica/input_parser.py
tests/modelica/test_input_parser.py

There was an unneeded weather bus in the TEASER outputs
* Add method to remove connections to input parser
* Remove weaBus, weaBus from TEASER outputs
* `pip install -r requirements.txt` 
* Run `py.test`
* Inspect results of `output/rc_order_4/Loads/B*/*.mo`
Fixes #28 
N/A

Remove redundant weather bus

---

geojson_modelica_translator/modelica/modelica_runner.py
tests/model_connectors/test_spawn.py
tests/model_connectors/test_spawn_ets.py
tests/model_connectors/test_time_series.py
tests/modelica/test_modelica_runner.py

Running multiple simulations in the same directory causes the results to be overridden.
* Move the results of the docker simulations into a results directory that has the project name prepended.
* Run `py.test`
#91

Clean up results of JModelica docker simulations

---

.travis.yml
setup.py

Somewhere along the way, the version of MBL is breaking the GMT. New ticket is here (#105).
* Lock MBL to version 2eb417f9ca2a9dce188988f1937bf79253daa9ff
* if the simulations fail, then print out the `stdout.log` to the screen
* Travis tests
#104

Use previous version of MBL and report logs

---

geojson_modelica_translator/system_parameters/system_parameters.py
tests/system_parameters/test_system_parameters.py

The original `get_param` method was a custom method to navigate a dictionary by delimiting on periods in a string.
* Use JsonPath as the mechanism to navigate a python dictionary (loaded from a JSON file)
* `py.test` should cover all the cases.
#63

Replace dot delimited strings with JsonPath

---

.gitignore
geojson_modelica_translator/geojson_modelica_translator.py
geojson_modelica_translator/model_connectors/spawn.py
geojson_modelica_translator/model_connectors/teaser.py
geojson_modelica_translator/model_connectors/teaser_ets_coupling.py
geojson_modelica_translator/model_connectors/templates/CouplingETS_TimeSeriesBuilding.mot
geojson_modelica_translator/model_connectors/templates/RunCouplingETS_TEASERBuilding.most
geojson_modelica_translator/model_connectors/templates/RunTeaserBuilding.most
geojson_modelica_translator/model_connectors/templates/RuntimeSeriesBuilding.most
geojson_modelica_translator/model_connectors/templates/teaser_building.mot
geojson_modelica_translator/model_connectors/templates/teaser_coupling.mot
geojson_modelica_translator/model_connectors/templates/teaser_coupling_ets.mot
geojson_modelica_translator/model_connectors/templates/time_series_building.mot
geojson_modelica_translator/model_connectors/time_series.py
geojson_modelica_translator/model_connectors/time_series_ets_coupling.py
geojson_modelica_translator/modelica/input_parser.py
geojson_modelica_translator/modelica/templates/package_base.mot
requirements.txt
tests/model_connectors/test_teaser.py
tests/model_connectors/test_teaser_ets.py
tests/model_connectors/test_time_series_ets.py
tests/modelica/data/test_1.mo
tests/modelica/test_package_parser.py

TEASER was using older versions of the parameters for the IBPSA/MBL RC models. 
* Requires a forked version of TEASER (https://github.com/urbanopt/TEASER/tree/rc-argument-names). This PR has yet to be submitted to TEASER.
* Move `use_moisture_balance` to forked teaser (this is temporary)
* Move `nports` to forked teaser (this is temporary)
* py.test should test the required functionality.
#51 #52

TEASER Parameter Names

---

geojson_modelica_translator/model_connectors/teaser.py
geojson_modelica_translator/model_connectors/teaser_ets_coupling.py
requirements.txt

We hacked in an nPorts and use_moisture_balance into TEASER which didn't belong.
* Uses an updated modelica builder version that allows us to add an argument/parameter to a component model. nPorts and user_moisure_balance are now added programatically.
`py.test`
n/a

Update to use component-modifications based on TEASER fix/update

---

geojson_modelica_translator/model_connectors/base.py
geojson_modelica_translator/model_connectors/spawn.py
geojson_modelica_translator/model_connectors/spawn_ets_coupling.py
geojson_modelica_translator/model_connectors/teaser.py
geojson_modelica_translator/model_connectors/teaser_ets_coupling.py
geojson_modelica_translator/model_connectors/time_series.py
geojson_modelica_translator/model_connectors/time_series_ets_coupling.py

First step in refactoring gmt
Removes `add_building` method from the spawn, teaser, & time_series model connectors, and consolidates into the base class. Base class is already the super of each of those model connectors, so this was a very simple non-breaking DRY-up.
`py.test tests/model_connectors/test_spawn.py` (or any of the model connector tests, or just py.test for everything)
#170

Add building in base

---

README.rst
requirements.txt
setup.py

We just released the first version of Modelica Builder and should use that version instead of the git version.
* Use Modelica-Builder from PyPI (0.1.0)
* Upgrade testing dependencies, requests, and jsonpath-ng. Others can be upgraded but they seemed too risky before release.
* `pip install -r requirements.txt`
* Verify that tests still run and pass with new dependency.
n/a

Use modelica builder from pypi

---

geojson_modelica_translator/geojson_modelica_translator.py
tests/geojson_modelica_translator/test_translator.py

The process_loads() method required the passing of the system parameters object.
* Remove the system_params from the process_loads. It is not needed because the geojson object already has the system_parameters file as a member variable. It is set by calling gj.set_system_parameters(<a_file_obj>)
* `py.test` should cover the tests
N/A

Do not pass system_params

---

requirements.txt

I was hoping to reconcile our version of TEASER with RWTH's. They have yet to release our changes.
* Point to UO's development branch of TEASER instead of rc-argument-names.
* eagerly update dependencies - `pip install -U --upgrade-strategy eager -r requirements.txt`
* `py.test`
#191

update teaser location

---

README.rst

Step for cloning the jmodelica repo is no longer necessary

docs: remove instruction for jmodelica setup

---

geojson_modelica_translator/model_connectors/templates/Network2Pipe_Instance.mopt

Previous instance of our network pipe had a hardcoded value of 2 for `iConDpSen` which would result in an out of bounds exception in the model compilation/simulation when only connecting a single ETS.
Uses the correct number based on number of connected ETSes
Dymola process if you feel its necessary

fix: use correct value for iConDpSen which is number of connected ETSes

---

geojson_modelica_translator/model_connectors/couplings/__init__.py
geojson_modelica_translator/model_connectors/districts/__init__.py
geojson_modelica_translator/model_connectors/energy_transfer_systems/__init__.py
geojson_modelica_translator/model_connectors/energy_transfer_systems/cooling_indirect.py
geojson_modelica_translator/model_connectors/energy_transfer_systems/heating_indirect.py
geojson_modelica_translator/model_connectors/networks/__init__.py
geojson_modelica_translator/model_connectors/plants/__init__.py
geojson_modelica_translator/model_connectors/plants/cooling_plant.py
geojson_modelica_translator/model_connectors/plants/heating_plant.py
geojson_modelica_translator/model_connectors/templates/TimeSeriesBuildingNew.mot
tests/model_connectors/test_district_heating_and_cooling_systems.py

GMT is working on improving flexibility/modularization of components/models
- demonstrates ability to combine district heating and cooling systems through tests
- some small fixes to accommodate the above example
- adds __init__ files to subpackages to simplify imports
Please run `geojson-modelica-translator/tests/model_connectors/test_district_heating_and_cooling_systems.py`, then load the resulting model into Dymola and verify things are correct.
Resolves #253

#253 feat: combined district heating and cooling

---

geojson_modelica_translator/model_connectors/couplings/templates/CoolingIndirect_NetworkChilledWaterStub/ComponentDefinitions.mopt
geojson_modelica_translator/model_connectors/couplings/templates/HeatingIndirect_NetworkHeatedWaterStub/ComponentDefinitions.mopt

We recently switched to a different timeseries load model. This broke some of our tests.
Fixes issue where some tests generated models where we are trying to grab values of conditional parameter (disFloCoo), which Modelica doesn't allow.
Specifically, this fixes the test_district_system_new.py test. The test would fail with the following error:
```
Error at line 96, column 27, in file ‘.../geojson-modelica-translator/tests/model_connectors/output/district_system_new/Districts/DistrictEnergySystem.mo’:
The component disFloCoo is conditional: Access of conditional components is only valid in connect statements
```
Example of failing test here:
https://github.com/urbanopt/geojson-modelica-translator/runs/1602675927#step:6:420
Run test_district_system_new.py successfully.

fix: use correct value for secMasFloRat

---

geojson_modelica_translator/modelica/lib/runner/jmodelica.py

With the fix, the model `tests/model_connectors/output/district_cooling_system/Districts/DistrictEnergySystem.mo` now takes 15 s to simulate with JModelica.
Note that the simulation time could be lowered down to about 10 s by setting `ncp = 500` instead of `5000` currently. The latter value is only needed for year-long simulations.

Fix simulation settings

---

geojson_modelica_translator/model_connectors/load_connectors/teaser.py
geojson_modelica_translator/model_connectors/model_base.py

This is a response to Michael Wetter's suggestion for improving the teaser modelica file
- Adds a conditional statement when adding `TAir` so it has the same instantiation rules as the upstream connector (otherwise if a user sets VAir and ATot to 0, the model is singular).
- Moves adding the TAir component a little lower in the code, to use the `thermal_zone_name` variable.
- Fixes a typo I left in model_base.py, unrelated to the rest of this PR.
`py.test tests/model_connectors/test_teaser.py`
- Confirm that tests/model_connectors/output/teaser_single/Loads/B5.../Floor.mo (or any of the *.mo files in there) contains an `if` statement on line 189
- And that the test passes, of course.
Resolves #300

Addressing Michael Wetter's suggestion for TAir

---

README.rst
pyproject.toml

previous main page on PyPi for this package was just the legal notice.  Previous version was [here](https://pypi.org/project/GeoJSON-Modelica-Translator/)
* show the README.rst file in pypi. Here is the version on the [test.pypi site](https://test.pypi.org/project/geojson-modelica-translator/0.2.1.2/)
* The image isn't showing up -- It may have to be an absolute link
* Can we list more than one author in PyPi? I can add you all as maintainers.
n/a
Start to fix this -- #194

Fix PyPi Main Page

---

README.rst

With the recent GMT release to pypi, we now have more stable pip installation. This provides documentation.
- Add a new section to the readme with `pip install` instructions
- Include basic reference to terminal help for documenting cli commands
Do the docs show up? Do they make sense?

update readme with pip installation instructions

---

management/uo_des.py

Apparently I didn't test enough situations for the cli earlier, and missed this path requirement
Makes path formulations for the modelica project dir explicit, enabling arbitrary location of project dir
Using the `create-model` cli command, give the `project_name` a path to somewhere that isn't pwd

fix path to modelica project dir

---

geojson_modelica_translator/model_connectors/couplings/templates/Spawn_CoolingIndirect/ComponentDefinitions.mopt
geojson_modelica_translator/model_connectors/couplings/templates/Spawn_CoolingIndirect/ConnectStatements.mopt
geojson_modelica_translator/model_connectors/couplings/templates/Spawn_HeatingIndirect/ComponentDefinitions.mopt
geojson_modelica_translator/model_connectors/couplings/templates/Spawn_HeatingIndirect/ConnectStatements.mopt
geojson_modelica_translator/model_connectors/load_connectors/spawn.py
geojson_modelica_translator/modelica/input_parser.py
tests/geojson_modelica_translator/test_translator.py
tests/model_connectors/data/spawn_district_system_params_ex1.json
tests/model_connectors/test_spawn_cooling.py
tests/model_connectors/test_spawn_district_heating_and_cooling_systems.py
tests/model_connectors/test_spawn_heating.py

Currently GMT only supports connecting spawn loads to stubbed out heating/cooling sources
Adds couplings to spawn load and heating cooling ETSes
Run the following tests, open the generated packages in dymola and verify everything looks correct
```
poetry run pytest ./tests/model_connectors/test_spawn_heating.py
poetry run pytest ./tests/model_connectors/test_spawn_cooling.py
poetry run pytest ./tests/model_connectors/test_spawn_district_heating_and_cooling_systems.py
```

feat: add spawn to ETS couplings

---

geojson_modelica_translator/model_connectors/couplings/templates/Teaser_CoolingIndirect/ComponentDefinitions.mopt
geojson_modelica_translator/model_connectors/couplings/templates/Teaser_CoolingIndirect/ConnectStatements.mopt
geojson_modelica_translator/model_connectors/couplings/templates/Teaser_HeatingIndirect/ComponentDefinitions.mopt
geojson_modelica_translator/model_connectors/couplings/templates/Teaser_HeatingIndirect/ConnectStatements.mopt
geojson_modelica_translator/model_connectors/load_connectors/teaser.py
geojson_modelica_translator/model_connectors/load_connectors/templates/TeaserCouplingBuilding.mot
tests/model_connectors/data/teaser_geojson_two_loads.json
tests/model_connectors/data/teaser_system_params_two_loads.json
tests/model_connectors/test_teaser_cooling.py
tests/model_connectors/test_teaser_district_heating_and_cooling_systems.py
tests/model_connectors/test_teaser_heating.py

Teaser only had couplings to ETS Stubs
Adds Teaser <> ETS heating and cooling indirect couplings
Run the following tests, open the generated packages in dymola and verify everything looks correct
```bash
poetry run pytest ./tests/model_connectors/test_teaser_heating.py
poetry run pytest ./tests/model_connectors/test_teaser_cooling.py
poetry run pytest ./tests/model_connectors/test_teaser_district_heating_and_cooling_systems.py
```
#380

feat: add teaser ets couplings

---

docs/_static/custom_sphinx_styles.css
geojson_modelica_translator/geojson/data/schemas/building_properties.json
geojson_modelica_translator/system_parameters/schema.json
management/update_schemas.py

The buildings and system parameters schema have many fields which are unused in the GMT. 
This PR added in an `[unused]` identifier to the fields that aren't currently read into the GMT templating framework.
* `cd docs`
* `make html`
*  Inspect the webpage
Resolves #347

Identify the unused schema fields

---

poetry.lock
pyproject.toml

We were using an older pyproject.toml section for `[build-system]`. This was causing an issue when requiring the package from another project.
New format is the following.
```
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
* make sure everything runs (`poetry update`, `poetry run py.test`)
Fixes #393

fix and update poetry dependencies

---

geojson_modelica_translator/model_connectors/districts/district.py
geojson_modelica_translator/model_connectors/load_connectors/load_base.py
geojson_modelica_translator/modelica/modelica_runner.py
management/uo_des.py
tests/management/test_uo_des.py
tests/modelica/test_modelica_runner.py

If a user has a space in their project name or directory tree, Modelica chokes and dies.
Adds graceful error message to user requiring them to remove spaces from name and path.
Project name gets tested for a space in automated testing now. `poetry run py.test tests/management/test_uo_des.py`
To test the tree, change something in your dir tree to include a space and try running `uo_des run-model`
Resolves #375

Alert user that Modelica doesn't support spaces in project name

---

poetry.lock
pyproject.toml

Automated tests have been including deprecation warnings. They are irritating.
- Update min Python version from 3.7 to 3.7.1, which enables:
- update pandas from existing 1.1.5 to 1.3.5. Current pandas is 1.4.2, which requires python 3.8
- run `poetry update`

update pandas to clear deprecation warning

---

geojson_modelica_translator/system_parameters/system_parameters.py

A user ran into this error and requested more information about where the files are expected to be.
Adds more detail to error message when building a sys-param file and modelica files from UO SDK are not found. We now share where the files are expected to be so the user can manually check.
Change [this line](https://github.com/urbanopt/geojson-modelica-translator/blob/better-error-messages/geojson_modelica_translator/system_parameters/system_parameters.py#L834) from `==` to `!=` and run the `uo_des build-sys-param` command, pointing to default output from the sdk. This will ensure the error gets raised, and the new text shown.
https://github.com/urbanopt/urbanopt-cli/issues/329

better error message if modelica timeseries files from sdk are not found

---

.github/workflows/ci.yml
CHANGELOG.rst
docs/getting_started.rst
geojson_modelica_translator/model_connectors/load_connectors/teaser.py
setup.cfg
tests/GMT_Lib/test_gmt_lib.py
tests/management/test_uo_des.py
tests/model_connectors/test_chilled_water_plant.py
tests/model_connectors/test_chp_system.py
tests/model_connectors/test_district_cooling_system.py
tests/model_connectors/test_district_heating_and_cooling_systems.py
tests/model_connectors/test_district_heating_system.py
tests/model_connectors/test_district_system.py
tests/model_connectors/test_heated_water_plant.py
tests/model_connectors/test_mixed_loads.py
tests/model_connectors/test_spawn.py
tests/model_connectors/test_spawn_cooling.py
tests/model_connectors/test_spawn_district_heating_and_cooling_systems.py
tests/model_connectors/test_spawn_heating.py
tests/model_connectors/test_teaser.py
tests/model_connectors/test_teaser_cooling.py
tests/model_connectors/test_teaser_district_heating_and_cooling_systems.py
tests/model_connectors/test_teaser_heating.py
tests/model_connectors/test_time_series.py
tests/model_connectors/test_time_series_heating_indirect.py
tests/model_connectors/test_time_series_mft_ets.py

Current tests rely on building and simulating the models in a single test method.
* Move the model assembly into the Test SetUp, then check the results in a build test
* Simulate the generated model if not marked as `not simulation`
* remove old pytest markers of `msl_v4` and `mbl_v9`
* remove testing with `issue2204_gmt_mbl` branch
* if tests pass, then should be good!
n/a

Break out build and simulate tests

---

.github/workflows/ci.yml

I often push commits and promptly realize I need to add something more. Then I end up with CI running on something I know is outdated or destined to fail. It's inefficient.
Automatically cancels an existing CI run of the same workflow when a new one is started. Only test the newest version!
Intentionally have poor form in your pushes?

automate canceling existing CI if a new one starts

---

.github/workflows/ci.yml
geojson_modelica_translator/modelica/lib/runner/README.md
geojson_modelica_translator/modelica/lib/runner/docker-compose.yml
geojson_modelica_translator/modelica/lib/runner/fmu_runner.py
geojson_modelica_translator/modelica/lib/runner/spawn.py
geojson_modelica_translator/modelica/lib/runner/spawn_docker.sh
geojson_modelica_translator/system_parameters/system_parameters.py
poetry.lock
pyproject.toml
tests/model_connectors/test_district_heating_and_cooling_systems.py
tests/modelica/test_modelica_runner.py
tests/system_parameters/test_system_parameters.py
tox.ini

Making the spawn compiling a little bit more user-friendly
- Passes arguments from GMT to the docker container for Spawn in a slightly different way
- Fixes the path handling in spawn.py
From the GMT root:
- `cd geojson-modelica-translator/modelica/lib/runner/`
- `docker compose build`
- `poetry run pytest ../../../../tests/modelica/test_modelica_runner.py::ModelicaRunnerTest::test_compile_in_docker`

Spawn docker named args

---

geojson_modelica_translator/model_connectors/load_connectors/spawn.py
geojson_modelica_translator/model_connectors/load_connectors/teaser.py
geojson_modelica_translator/model_connectors/plants/cooling_plant.py
geojson_modelica_translator/system_parameters/schema.json
geojson_modelica_translator/system_parameters/system_parameters.py
geojson_modelica_translator/system_parameters/time_series_microgrid_template.json
geojson_modelica_translator/system_parameters/time_series_template.json
management/data/baseline_sys_params.json
tests/data_shared/geojson_district/system_params.json
tests/data_shared/mixed_loads_district/system_params.json
tests/data_shared/system_params_microgrid_example.json
tests/geojson_modelica_translator/data/system_parameters_mix_models.json
tests/model_connectors/data/spawn_system_params_ex1.json
tests/model_connectors/data/teaser_system_params_ex1.json
tests/model_connectors/data/teaser_system_params_two_loads.json
tests/model_connectors/data/time_series_system_params_chp.json
tests/model_connectors/data/time_series_system_params_ets.json
tests/model_connectors/data/time_series_system_params_massflow_ex1.json
tests/model_connectors/data/time_series_system_params_no_ets.json
tests/system_parameters/data/system_params_1.json
tests/system_parameters/data/system_params_2.json
tests/system_parameters/test_system_parameters.py

@amyeallen1 found some brittleness in our existing use of weather files. This completes the weather file location work, superseding her excellent attempts that were thwarted by the old schema.
- Moves weather file to top-level in the sys-param files
- Assumes `epw` file is same name & location as `mos` weather file (for spawn)
- This is a valid assumption for sys-params built by the CLI
- Updates the sys-param test file to work with new schema
- Resolves #461 
- Supersedes #483

Weather file at top level

---

.github/workflows/ci.yml
docs/developer_resources.rst

Our CI should test the appropriate settings and environments
#513  failed CI which made this solution apparent. Merging this PR should make CI pass in that PR.
- Explicitly use Ubuntu 20.04 because apparently 22.04 doesn't support Python 3.7
- Add the Github Token secret to make Coveralls happy
- Explicitly point to the MBL 9.1 branch, instead of master
- Adds the message command currently required with pytest to not run compilation or simulation tests

Improve ci config settings

---

geojson_modelica_translator/system_parameters/system_parameters.py

I removed a duplicate casting to float in #507 but it turns out there are cases where the second casting is required. My current theory is that `building_type: "lodging"` in the geojson file means `massFlowRateHeating` for the entire building is zero, even in a Mixed Use building if lodging is a non-zero percentage of the building. This zero, in turn, broke system_parameters.py by being an int and not a float.
Force casting to float when mfrt heating load is 0

bugfix of the bugfix, yay

---

.github/workflows/ci.yml
poetry.lock
pyproject.toml

Versions of flake8 and new BuildingsPy now require python 3.8

Remove support for 3.7 in development, update development dependencies

---

geojson_modelica_translator/model_connectors/load_connectors/templates/TimeSeries_Instance.mopt

We found our time-series instance template was missing information about the available ports
Specifies that there are one each of input/output ports for hot and cold water

specify ports for each time series building in instance template

---

geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX.mot
geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX.py
geojson_modelica_translator/modelica/modelica_mos_file.py
tests/GMT_Lib/test_gmt_lib_des.py
tests/modelica/data/B2_no_water_load.mos
tests/modelica/test_modelica_mos.py

We were parsing the MOS file by hand, the sizing of the mass flow rate was fixed, and the plant flow rate.
* Add a new class to read in an MOS file. The class can read the variables in the header and can set variable values.
* Refactor the reading of the water heating load to use the new class
* Expose the plant mass flow rate to the DES5G mot file
* Size the mass flow rates according to the total heating/cooling load, delta T, and Cp
* Ideally, generate the DES_5G test and run in Dymola (I confirmed that it ran)
* The unit tests should cover the MOS file class
n/a

Add MOS file wrapper and size the 5G mass flow rate

---

geojson_modelica_translator/modelica/lib/runner/om.py
geojson_modelica_translator/modelica/modelica_runner.py
tests/model_connectors/test_mixed_loads.py

It is not always desired to remove all the config and output files from the simulation
Add a keyword arg to the `run_in_docker` and `cleanup_path` methods to not remove all the files upon simulation completion.
Ideally, use a Jupyter Notebook to test running w/ and w/o the debug flag.
```
mr = ModelicaRunner()
success, _ = mr.run_in_docker('compile_and_run', 'baseline.Districts.district', 
run_path=analysis_baseline_dir,
file_to_load=(analysis_baseline_dir / 'package.mo'),
start_time=0, stop_time=86400, step_size=300,
debug=True)
```
and 
```
mr = ModelicaRunner()
success, _ = mr.run_in_docker('compile_and_run', 'baseline.Districts.district', 
run_path=analysis_baseline_dir,
file_to_load=(analysis_baseline_dir / 'package.mo'),
start_time=0, stop_time=86400, step_size=300)
```
n/a
n/a

Add simulation flag to not remove all output files

---

geojson_modelica_translator/modelica/GMT_Lib/Electrical/AC/ThreePhasesBalanced/Loads/Inductive.py
geojson_modelica_translator/modelica/GMT_Lib/Electrical/AC/ThreePhasesBalanced/Sources/generators.py
tests/GMT_Lib/test_gmt_lib.py
tests/data_shared/system_params_microgrid_example.json

The Modelica template for inductive electric load was getting invalid info from the test sys-param file. Now we're reading from the correct section of the sys-param and loading the data properly into the template.
Reads electrical load values for each building to help generate a microgrid
The automated test for `tests/GMT_Lib/test_gmt_lib.py::test_simulate_inductive_load` should be sufficient, but there are still issues with OpenModelica that need to be resolved. Running by hand with Dymola will verify that the template reads data from the sys-param file and properly generates a working model. There is also a test that builds the model, so it can be inspected by hand at `tests/GMT_Lib/output/Inductive/Inductive0.mo`.
Resolves #555

Read correct data from sys-param for microgrid electrical load

---

.github/workflows/ci.yml
poetry.lock

CI has been failing a lot when installing dependencies with Poetry. Hopefully upgrading Poetry will make that go away.
Upgrade Poetry in CI from 1.4.2 -> 1.5.1
Automated tests. If everything passes on the first try, this is a win.

upgrade poetry version in ci to 1.5.1

---

geojson_modelica_translator/modelica/lib/runner/om_docker.sh
geojson_modelica_translator/modelica/modelica_runner.py

When running tests developers often `ctrl-c` to cancel a test midway through a long-running simulation. The container is then left alive unnecessarily which is a resource drain.
Catch KeyboardInterrupt while simulating and `kill` all containers from the `gmt-om-runner` image
- Start a simulation test
- For instance `tests/GMT_Lib/test_gmt_lib.py::test_simulate_cooling_plant`
- `ctrl-c` once the simulation begins
- `docker ps -a` to check that containers from the image are removed
Resolves #384

Stop and remove containers if user cancels a simulation

---

geojson_modelica_translator/modelica/lib/runner/Dockerfile

OMC 1.21 does not work with the 7-building example file
Downgrade the Dockerfile to pull from openmodelica:1.20-gui
New image has already been pushed to dockerhub. The CI should handle the tests.
n/a

Downgrade to OMC 1.20

---

geojson_modelica_translator/model_connectors/plants/borefield.py
geojson_modelica_translator/system_parameters/schema.json
tests/model_connectors/data/system_params_ghe.json

The code to read the ghe_dir worked, but was brittle - it only worked if the user was in the GMT root.
Borefield.py now checks if the path supplied by the user in the sys-param file is absolute, and if so, uses it. If it's not absolute, it assumes the path is relative to the sys-param file. The schema entry was updated to say exactly that.
Try supplying either an absolute path or a path relative to the sys-param file (`./`) and running tests/model_connectors/test_borefield.py::test_build_district_system. Try supplying bogus paths to confirm the graceful error message appears.

Improve gfunction path

---

geojson_modelica_translator/geojson/urbanopt_geojson.py

When running the GMT via the CLI on a Windows computer we found a situation where we could reference a variable before assigning it.
Initialize the variable as an empty string first.

initialize empty variable before potential use

---

.cspell.json
geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_partial.mot
geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX.mot
geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX.py
geojson_modelica_translator/modelica/modelica_project.py
geojson_modelica_translator/modelica/simple_gmt_base.py
tests/GMT_Lib/test_gmt_lib_des.py

Many of the 'operational' variables of the 5G systems are buried in the partial model within the MBL. Need to expose the model to the GMT to allow for model manipulation.
* template the PartialSeries model
* update the Simple GMT Base to allow passing a dict of 'template' models to replace. In a very simple way.
* code review
* CI 
* Generate 5G_DES model and run in dymola.
n/a

Include 5G partial model in generation

---

.cspell.json
geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX.mot
geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX_variable.mot
geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX_variable.py
geojson_modelica_translator/system_parameters/system_parameters.py
tests/GMT_Lib/test_gmt_lib_des.py

The existing 5G DES model had a constant volume distribution loop which consumed a large amount of energy during low load scenarios.
Add variable speed pump and controller to main distribution loop.
CI + Dymola run of (5G_Variable) test model.
n/a

Add model for controlled distribution loop mass flow rate

---

geojson_modelica_translator/system_parameters/system_parameters.py

The System Parameter file generation hard codes the `modelica.mos` name.
* Provide a kwarg to pass in the name of the Modelica load file to use. This is used when we manipulate the modelica load files before reading them into UO DES.
* Not sure we need to test, just review the code.
N/A

Allow user to specify Modelica load filename

---

geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_partial.mot
geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX_variable.mot

The mass flow rate of the GHX was set to the same gain as the distribution mass flow rate. This caused a very large GHX mass flow rate (and resulting energy consumption) due to the GHX pump running at a very high rate, continuously.
Secondly, the facMul was set to 10, which I think is not needed.
* Adds new gain block to send to the GHX pump
* Default the facMul to 1, not 10!
Unit tests should run!
n/a
Values much better align with OpenStudio!

Decouple gain for distribution and ghx mass flow rates

---

geojson_modelica_translator/model_connectors/networks/templates/NetworkDistributionPump_Instance.mopt
geojson_modelica_translator/system_parameters/schema.json
geojson_modelica_translator/system_parameters/time_series_microgrid_template.json
geojson_modelica_translator/system_parameters/time_series_template.json
management/data/baseline_sys_params.json
tests/model_connectors/data/system_params_ghe.json
tests/model_connectors/data/system_params_ghe_2.json

MBLv10 has changes to their pump model which sets an upper bound to the actual pump head based on the nominal head. This has caused the 5G district models to fail if the nominal pump head is not set correctly.
This PR fixes the above issue by allowing the users to change the nominal district pump head from the system parameters file.
poetry run pytest -m 'not dymola' tests/model_connectors/test_district_single_ghe.py
#609

Add district nominal pump head to system parameters file

---

geojson_modelica_translator/model_connectors/plants/templates/HeatingPlantWithCHP.mot
geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX.mot
geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX.py
geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX_variable.mot
geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX_variable.py
geojson_modelica_translator/modelica/lib/runner/Dockerfile
geojson_modelica_translator/modelica/lib/runner/README.md
geojson_modelica_translator/modelica/modelica_runner.py
pyproject.toml
tests/GMT_Lib/test_gmt_lib_des.py
tests/model_connectors/test_chp_system.py

- Our GMT_lib tests were failing in the new MBLv10 world. It turns out there is something in Ubuntu 22 that doesn't work with [this MBL model](https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Experimental/DHC/Examples/Combined/SeriesConstantFlow.mo) that works fine in Ubuntu 20. Downgrading an Ubuntu version means maintaining more of the OM Docker installation code ourselves 👎.
- Fix & re-enable the CHP model that has been skipped for a while
- Duplicates most of the OM dockerfile so we can set our own Ubuntu version
- Use the new Docker image in modelica_runner.py
- Re-enables the tests that were skipped because of this bug
- Update the Dockerfile version in the readme
- Bump to version 0.6.0 for the GMT
- Use a new boiler model in the CHP model
- Test the CHP model …

Use Ubuntu 20 and fix CHP model

---

.coveragerc
docs/developer_resources.rst
docs/getting_started.rst

The way we release the library in general and the documentation for this library has been updated. The instructions now match reality.
- Remove references to JModelica that were left over from the bad old days
- Make the documentation release instructions match our current practices

Update instructions for releasing documentation publicly

---

geojson_modelica_translator/model_connectors/plants/chp.py
geojson_modelica_translator/model_connectors/plants/templates/Boiler_TParallel_v10.mo
geojson_modelica_translator/model_connectors/plants/templates/CentralHeatingPlant.mo
geojson_modelica_translator/model_connectors/plants/templates/HeatingPlantWithCHP.mot
geojson_modelica_translator/model_connectors/plants/templates/PartialPlantParallel_v10.mo
geojson_modelica_translator/modelica/lib/runner/README.md

We had to make some new models to support MBLv10. They were just named `..._new` which could get confusing once we forgot when/why these were created.
- Renames 2 models to clarify that they work with/are intended for MBLv10
- Update Docker readme to reference current version of our Dockerfile
- This is not substantive. I happened to notice it when rebuilding the image locally
@nllong What naming convention should we use?
Resolves #612

Rename new modelica models to clarify MBL version

---

management/uo_des.py
tests/management/test_uo_des.py

I found a bug in uo-cli when it was calling gmt-cli, which inspired me to look at gmt-cli. Found there were a few inconsistencies and missing documentation, so I cleaned that up. Then needed to update the tests because of it.
- Make a few Click arguments `options` instead
- This is consistent with the rest of our CLI, and properly categorizes required and optional arguments in the help text
- Add help text for new & existing cli options
- Update test call due to these changes
[This PR](https://github.com/urbanopt/urbanopt-cli/pull/449) in the UO-CLI fixes the wrapper to our cli, and inspired this investigation.

Minor improvements to the CLI

---

geojson_modelica_translator/system_parameters/schema.json

We didn't clarify the unit for GHE flow_rate we're sending to GHEDesigner, via ThermalNetwork.
- Add units to GHE flow_rate in the schema
Have @mitchute tell you it's right 😆

Specify units of GHE flow_rate

---

geojson_modelica_translator/model_connectors/districts/district.py
geojson_modelica_translator/model_connectors/model_base.py
geojson_modelica_translator/model_connectors/plants/borefield.py
geojson_modelica_translator/modelica/GMT_Lib/DHC/Components/Plants/Heating/boiler_polynomial.py
geojson_modelica_translator/modelica/GMT_Lib/Electrical/AC/ThreePhasesBalanced/Loads/Inductive.py
geojson_modelica_translator/modelica/GMT_Lib/Electrical/AC/ThreePhasesBalanced/Loads/capacitive.py
geojson_modelica_translator/modelica/GMT_Lib/Electrical/AC/ThreePhasesBalanced/Sources/generators.py
geojson_modelica_translator/modelica/GMT_Lib/Electrical/AC/ThreePhasesBalanced/Sources/grid.py
geojson_modelica_translator/modelica/modelica_runner.py
geojson_modelica_translator/system_parameters/system_parameters.py
geojson_modelica_translator/utils.py
tests/modelica/test_modelica_runner.py

MBLv10 requires a value in the Service Hot Water column of the loads timeseries, even if it isn't used. Modelica-Builder [has a feature](https://github.com/urbanopt/modelica-builder/blob/develop/modelica_builder/modelica_mos_file.py#L93) that can update values in .mos files, so lets use that.
_The UO SDK populates this column as of v0.11.0 with https://github.com/urbanopt/urbanopt-reporting-gem/pull/143. Load files generated before then may be missing this data._
- Uses the modelica-builder method to set SHW load to 1/10 of the heating load or 5000W, whichever is higher.
- Improve logging a bit
Generate a model using timeseries data that does not have the SHW column populated. The updated file is `modelica_project/Loads/Resources/Data/<buildingname>/<load_timeseries>.mos`

Force a dummy value for SHW in modelica loads even if not present

---

poetry.lock
pyproject.toml

The main urbanopt SDK was having troubles with incompatible dependencies. Pandas was the primary culprit. Relaxing this version constraint among all the relevant packages will help us escape dependency hell.
- Python has their general [dependency specification](https://packaging.python.org/en/latest/specifications/version-specifiers/#compatible-release)
- Poetry has [their own specification](https://python-poetry.org/docs/dependency-specification/)
Allows Pandas >=2 <3
CI is sufficient for the mechanics. Happy to have a philosophy discussion if there is a preferred technique to escape dependency hell.
https://github.com/urbanopt/urbanopt-cli/issues/459

Relax pandas version requirement

---

geojson_modelica_translator/system_parameters/schema.json
geojson_modelica_translator/system_parameters/time_series_template.json

We should have a user-configurable 5G heat-pump. COP values are important to be able to customize.
-  [x] Add `cop_c` and `cop_h` to schema
Confirm that [this test](https://github.com/urbanopt/geojson-modelica-translator/blob/develop/tests/management/test_uo_des.py#L52) generates a sys-param file (saved into [this folder](https://github.com/urbanopt/geojson-modelica-translator/tree/develop/tests/management/data/sdk_project_scraps/run/baseline_scenario)) that includes `district_system.fifth_generation.wahp`.

Add default cop values for 5G district heat pump efficiencies

---

.github/workflows/ci.yml

On July 29 Github Actions [removed access to Docker Compose v1](https://github.com/actions/runner-images/issues/9692) (which has been deprecated since July 2023). This means we have to use the v2 syntax, which this PR achieves.
_Since we have this in an early step of our CI workflow, all CI will fail until this is merged._
Use Docker Compose v2 syntax in a CI check

Update Docker command in CI to work with current syntax

---

geojson_modelica_translator/model_connectors/load_connectors/spawn.py
geojson_modelica_translator/model_connectors/load_connectors/teaser.py
geojson_modelica_translator/model_connectors/load_connectors/time_series.py
geojson_modelica_translator/model_connectors/load_connectors/time_series_mft_ets_coupling.py
tests/model_connectors/test_time_series_mft_ets.py

This will simplify access to results of Modelica simulations by naming the Modelica variables with the geojson_id of the load (building). Future work should do the same thing for borefields when modeling GHEs.
Update `self.id` for the loads to use the geojson_id instead of generating a simple_uuid. We retain simple_uuid for objects that aren't being supplied by the geojson file, such as networks, couplings, ETSs, etc.
Resolves #645

Use feature ids in load names instead of simple_uuid

---

geojson_modelica_translator/system_parameters/system_parameters.py
tests/management/data/sdk_project_scraps/example_project_germany_ghe.json
tests/management/test_uo_des.py
tests/system_parameters/test_system_parameters.py

We were only supporting USA weather locations until now. This PR enables any location from www.energyplus.net/weather to be used (as of Sep 4, 2024). _**Major caveat**_: This only accepts *.mos weather files, which as of now are only available on the website for USA locations. Once mos weather files for all locations on the website are available, this code is ready to take advantage.
- Handle all locations provided by https://energyplus.net/weather. Requires a weather file in *.mos format to be avaailable from that website, which as of today is limited to USA locations.
- Adds tests for this using the CLI and using the code directly
Provide a valid weather epw filename for any location outside the USA in your geojson file. Observe that the EPW is downloaded correctly and an error is …

Support international weather locations

---

.gitignore

#654 added new tests which download new weatherfiles. That test output isn't required to be stored in github.
Gitignore German weather files downloaded via https://github.com/urbanopt/geojson-modelica-translator/blob/develop/tests/management/test_uo_des.py#L73

Add downloaded weatherfiles to gitignore

---

management/uo_des.py

The UO cli was also supplying default values to this cli (in addition to our own default values), which caused collisions in the `create-model` case. Documented in [this issue](https://github.com/urbanopt/urbanopt-cli/issues/480) and resolved in [this PR](https://github.com/urbanopt/urbanopt-cli/pull/486) in the main uo-cli repo.
During diagnosis of that behavior, I learned about additional validation available in [click.Path](https://click.palletsprojects.com/en/8.1.x/api/#click.Path) which I implemented here.
- Sets `path_type` for cli arguments, so they can be used directly in the code (instead of being read as strings, the previous behavior)
- Add a validation step where Click checks that the path leads to a readable file.

Improve cli typing & validation

---

geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX.py
geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX_variable.py
poetry.lock
pyproject.toml
tests/system_parameters/test_system_parameters.py

For the constant and variable DES systems, if there was a single building, then the model would fail to build.
If the jsonpath returns a dict, then it will assume it is a single building. This is not common, but needed for the aggregated load analysis.
unit tests should pass
n/a

Support single building DES templates

---

geojson_modelica_translator/geojson_modelica_translator.py
geojson_modelica_translator/model_connectors/load_connectors/load_base.py
geojson_modelica_translator/model_connectors/load_connectors/teaser.py
geojson_modelica_translator/system_parameters/system_parameters.py

A while ago we removed the 'defaults' section of sys-param files. This removes the code for reading those sections.
Refactor the `get_param` code in system_parameters.py to remove references to defaults which haven't existed for some time.
Resolves #495

Clean up sys-param code that reads parameters

---

geojson_modelica_translator/model_connectors/couplings/5G_templates/UnidirectionalSeries_Borefield/ConnectStatements.mopt
geojson_modelica_translator/model_connectors/load_connectors/load_base.py
geojson_modelica_translator/model_connectors/load_connectors/templates/TimeSeriesBuildingWithETS.mot
geojson_modelica_translator/model_connectors/load_connectors/templates/TimeSeries_Instance.mopt

This PR changes the couplings to put GHEs downstream of the buildings in the same building group.
Before:
After:
It also changes the time series building template to take heat pump heating COP from the sys_params file.
poetry run any tests with GHEs and buildings.
Issue #675 and issue #666.

Putting GHEs downstream of the buildings

---

.github/workflows/documentation_site.yml
CHANGELOG.md
docs/docs_requirements.txt
pyproject.toml

I accidentally put the wrong link for the documentation site. Fixed it.
I got too antsy to fix this, and pushed directly to develop (shame!). The commit that has the fix is https://github.com/urbanopt/geojson-modelica-translator/commit/d52c6599999dc59df01965b87ad696cfb78030c0
New links to the live docs site

Release v0.9.1-rc1

---

geojson_modelica_translator/model_connectors/networks/ground_coupling.py

Some weather file names weren't being parsed correctly when looking up soil temp coefficients. Frankfurt was the first example we found of this. This handles those cases.
If soil temp coeff lookup fails, try using only the first word of the station and capitalizing it. If that still doesn't work, error as before.
Build a demo project with the uo-cli, using with the [Frankfurt weather file](https://energyplus.net/weather-location/europe_wmo_region_6/DEU/DEU_Frankfurt.am.Main.106370_IWEC). Go through the default baseline workflow, and `uo_des create-model`. If that works successfully (it did on my machine! 😄 ) we're good to go

Handle all-caps soil-temp stations, like Frankfurt

---

tests/model_connectors/data/sdk_output_skeleton_13_buildings/exportGeo.json
tests/model_connectors/data/time_series_ex2.json

Removed `is_ghe_start_loop` from schema in https://github.com/urbanopt/urbanopt-geojson-gem/pull/280 because it is how being handled automagically [in ThermalNetwork](https://github.com/NREL/ThermalNetwork/pull/58).
- Remove this property from test geojson files

Remove `is_ghe_start_loop` from test geojson files

---

geojson_modelica_translator/geojson_modelica_translator.py
geojson_modelica_translator/model_connectors/couplings/coupling.py

- Explicitly selects actions for 4th & 5th generation districts. Old technique was to assume that anything non-5th-gen was 4th gen. This enables additional generations of district systems to be modeled in the future, opening up development opportunities.
- DRY up gmt.py a bit.
CI is suffcient
Resolves #504

Clean up matching district generation types

---

.gitignore
geojson_modelica_translator/system_parameters/system_parameters.py
management/uo_des.py
ruff.toml
tests/system_parameters/test_system_parameters.py

In cases where a user wants to run UO without an internet connection, they will need to provide their own epw & mos weather files. This not only exposes the existing functionality to the cli, we now also look in multiple common locations in the users' project folder for weather.
- Expose `skip_weather_download` to the cli
- Look for weather in multiple locations, not just the dir the sys-param file is in
- Update existing tests to work with the new weather location ideas
Run the cli by hand, with the new `-w` flag.
- Is `-w` a good short flag for weather? It's to skip downloading and use an existing file
I tried logging when we download and when we use a local file (which would have been useful for testing), and it wasn't showing on my stdout. Not sure why, so I am ignoring that for now.

Expose skipping weather download

---

geojson_modelica_translator/modelica/lib/runner/simulate.most
geojson_modelica_translator/modelica/modelica_runner.py
management/uo_des.py
tests/management/test_uo_des.py

This enables selecting specific output variables for the Modelica simulation to emit, using [regex or wildcards](https://openmodelica.org/doc/OpenModelicaUsersGuide/1.24/omedit.html#output). I was also able to clean up the simulate.most templated script that we use to send the actual command to Modelica.
Enables new filtering functionality for the Modelica simulation
Run the `tests/management/test_uo_des.py::test_cli_runs_existing_5g_model_with_specific_variables` test and manually open the results file in OM to review the output. Confirm that the `PPum` variable is not available because that test does not specifically include it in the list of variables we are interested in.

Enable selecting output variables from Modelica simulation

---

geojson_modelica_translator/modelica/modelica_runner.py
management/uo_des.py
tests/management/test_uo_des.py

OpenModelica has many options it can accept during compilation and simulation that we weren't taking advantage of.
For usage, review the [compiler flag documentation](https://openmodelica.org/doc/OpenModelicaUsersGuide/1.24/omchelptext.html) and the [simulation flag documentation](https://openmodelica.org/doc/OpenModelicaUsersGuide/1.24/simulationflags.html). For help with the `variable_filter`, see [this documentation](https://openmodelica.org/doc/OpenModelicaUsersGuide/1.24/omedit.html#output).
Enables compiler flags and simulation flags to be passed to the `uo_des run-model` command, which are used by OpenModelica. This enables, among many other things:
- limiting the variables in the output
- viewing additional debug info from the simulation run
- removing some non-timestep outputs
- …

Add capability to pass Modelica flags to the GMT CLI

---

geojson_modelica_translator/system_parameters/system_parameter_properties.json
tests/system_parameters/data/system_params_ghe.json
tests/system_parameters/data/system_params_ghe_predesigned.json
tests/system_parameters/test_system_parameters.py

To help ThermalNetwork decide when to autosize GHE components, we now require the `autosized` flags to be present in the sys-param file.
- Update the schema to require autosize flags in sys-params
- Update a test file and test with the newly required fields
CI can test the validity of the schema, that's all that's happening with this here, for now.

Require autosize flags in sys-param files
