- geojson_modelica_translator/modelica/templates/package_base.mot
- requirements.txt
Update requirements.txt file to use new fork of TEASER until we can reconcile the differences.
https://github.com/urbanopt/TEASER/blob/mbl-7.0/teaser/data/output/modelicatemplate/IBPSA/IBPSA_OneElement
https://github.com/urbanopt/TEASER/blob/mbl-7.0/teaser/data/output/modelicatemplate/IBPSA/IBPSA_TwoElements
https://github.com/urbanopt/TEASER/blob/mbl-7.0/teaser/data/output/modelicatemplate/IBPSA/IBPSA_ThreeElements
https://github.com/urbanopt/TEASER/blob/mbl-7.0/teaser/data/output/modelicatemplate/IBPSA/IBPSA_FourElements
Fixes #6
> Updated TEASER RC Model Names

- CHANGELOG.rst
- geojson_modelica_translator/model_connectors/teaser.py
- requirements.txt
- tests/test_translator.py
This PR updates the latest version of teaser (version 0.7.2). This also removes the dependency on the fork of TEASER, we are now pointing to the main teaser repo again.
Addresses: #29
> update to latest teaser

- geojson_modelica_translator/modelica/modelica_runner.py
- tests/model_connectors/test_spawn.py
- tests/test_translator.py
The simulation needs to occur at the same level as the project in JModelica.
> shift run dir up to project level

- .coveragerc
- geojson_modelica_translator/model_connectors/templates/time_series_building.mot
- geojson_modelica_translator/model_connectors/templates/time_series_coupling.mot
- geojson_modelica_translator/model_connectors/time_series.py
- geojson_modelica_translator/system_parameters/schema.json
- setup.cfg
- tests/model_connectors/data/time_series_system_params_ex1.json
Need to make the name of the methods and files consistent.
* Small cleanup on file names and variable names.
* remove jmodelica and mos files from test coverage.
`py.test`
N/A
> Filename and method syntax

- geojson_modelica_translator/model_connectors/teaser.py
- geojson_modelica_translator/modelica/input_parser.py
- tests/modelica/test_input_parser.py
The fraction latent of a person was being set directly and not using a modelica parameter.
* Update input parser to support adding new parameters
* Add fraLat with a description when post processing the TEASER output.
* py.test -- all tests should pass. 
#94
> Fraction Latent as a Parameter

- CHANGELOG.rst
- geojson_modelica_translator/geojson/schemas.py
- geojson_modelica_translator/geojson/urbanopt_geojson.py
- geojson_modelica_translator/model_connectors/spawnBui_ETS_Coupling.py
- geojson_modelica_translator/system_parameters/schema.json
- geojson_modelica_translator/system_parameters/system_parameters.py
- requirements.txt
- setup.py
- tests/model_connectors/data/spawn_system_params_ex1.json
- tests/model_connectors/test_ets.py
- tests/system_parameters/data/system_params_1.json
- tests/system_parameters/data/system_params_2.json
- tests/system_parameters/test_system_parameters.py
The system parameter schema was malformed. 
* Fix JSON schema to conform to standard
* Add ETS to the schema
* Fix spawn ETS coupling
* Fix warnings of unclosed files
* Update dependencies (GeoJSON and JSONSchema)
* `py.test` should cover functionality
* Code review
Address #87
> Fix invalid system parameter schema

- .gitignore
- .travis.yml
- geojson_modelica_translator/geojson_modelica_translator.py
- geojson_modelica_translator/model_connectors/ets_template.py
- geojson_modelica_translator/model_connectors/templates/CoolingIndirect.mot
- geojson_modelica_translator/modelica/input_parser.py
- geojson_modelica_translator/system_parameters/system_parameters.py
- requirements.txt
- setup.py
- tests/model_connectors/test_ets.py
- tests/model_connectors/test_spawn.py
- tests/model_connectors/test_spawn_ets.py
- tests/model_connectors/test_time_series.py
- tests/model_connectors/test_time_series_ets.py
> Fix ets to not read schema

- geojson_modelica_translator/model_connectors/teaser.py
- requirements.txt
- tests/system_parameters/test_system_parameters.py
Exposure of RC interfaces and propagate two parameters.
> Rc models exposed connectors

- geojson_modelica_translator/model_connectors/teaser.py
corrected nPort default number to 0.
> corrected default nPorts.

- geojson_modelica_translator/model_connectors/templates/BuildingSpawnZ6WithCoolingIndirectETS.mo
- geojson_modelica_translator/model_connectors/templates/CentralCoolingPlant.mo
- geojson_modelica_translator/model_connectors/templates/ChilledWaterPumpSpeed.mo
- geojson_modelica_translator/model_connectors/templates/ChillerStage.mo
- geojson_modelica_translator/model_connectors/templates/ConnectionParallel.mo
- geojson_modelica_translator/model_connectors/templates/CoolingTowerParallel.mo
- geojson_modelica_translator/model_connectors/templates/CoolingTowerWithBypass.mo
- geojson_modelica_translator/model_connectors/templates/DesignDataParallel4GDC.mo
- geojson_modelica_translator/model_connectors/templates/HydraulicHeader.mo
- geojson_modelica_translator/model_connectors/templates/PartialBuilding.mo
- geojson_modelica_translator/model_connectors/templates/PartialBuildingETS.mo
- geojson_modelica_translator/model_connectors/templates/PartialBuildingWithCoolingIndirectETS.mo
- geojson_modelica_translator/model_connectors/templates/PartialDistribution.mo
- geojson_modelica_translator/model_connectors/templates/PipeConnection.mo
- geojson_modelica_translator/model_connectors/templates/PipeDistribution.mo
- geojson_modelica_translator/model_connectors/templates/UnidirectionalParallel.mo
Reformats the modelica files in templates dir.
This uses modelica-fmt version 0.1-pr2
> format .mo files with modelica-fmt

- README.rst
The README file was out of date.
* Fix the running examples using jm_ipython section.
* Move the setting up of the MBL into the required installation section.
* run through the installation and example simulations.
* Run the python script manually to create the PNG.
#207
> Update running examples in the README

- geojson_modelica_translator/model_connectors/couplings/coupling.py
- geojson_modelica_translator/model_connectors/couplings/templates/Spawn_EtsColdWaterStub/ComponentDefinitions.mopt
- geojson_modelica_translator/model_connectors/couplings/templates/Spawn_EtsColdWaterStub/ConnectStatements.mopt
- geojson_modelica_translator/model_connectors/couplings/templates/Spawn_EtsHotWaterStub/ComponentDefinitions.mopt
- geojson_modelica_translator/model_connectors/couplings/templates/Spawn_EtsHotWaterStub/ConnectStatements.mopt
- geojson_modelica_translator/model_connectors/energy_transfer_systems/ets_cold_water_stub.py
- geojson_modelica_translator/model_connectors/load_connectors/spawn_new.py
- geojson_modelica_translator/model_connectors/templates/EtsColdWaterStub_Instance.mopt
- geojson_modelica_translator/model_connectors/templates/Spawn_Instance.mopt
- geojson_modelica_translator/utils.py
- tests/model_connectors/test_spawn_new.py
Part of larger effort refactoring existing models into a more flexible design using "couplings". 
Creates the Spawn load, and heating stub coupling.
Run the unittests and verify the generated `spawn_single_new` model in Districts looks correct, and is loadable into Dymola.
#225 (though it does not complete it)
> feat: add spawn load and hot water ets stub for coupling design

- geojson_modelica_translator/model_connectors/templates/SpawnBuilding.mot
- geojson_modelica_translator/model_connectors/templates/Spawn_Instance.mopt
Moves parameters that we don't change into Spawn model itself. Eventually these will be templated here inside the model.
Please run the test for test_spawn_new.py, then load the resulting package into Dymola, and make sure it runs correctly.
> refactor: set default temperature values for spawn load

- geojson_modelica_translator/model_connectors/couplings/graph.py
- geojson_modelica_translator/model_connectors/districts/district.py
- tests/model_connectors/test_district_system_new.py
- tests/model_connectors/test_spawn_new.py
- tests/model_connectors/test_teaser_new.py
Current and future challenges of GMT necessitate a centralized graph representation of connected systems.
Creates a class to represent this graph of systems.
There was no change to actual behavior, just refactored into a new class. If you really want to, run the *_new.py tests and load them into Dymola
> feat: coupling graph

- geojson_modelica_translator/model_connectors/couplings/templates/HeatingIndirect_NetworkHeatedWaterStub/ConnectStatements.mopt
- geojson_modelica_translator/model_connectors/couplings/templates/TimeSeries_HeatingIndirect/ComponentDefinitions.mopt
- geojson_modelica_translator/model_connectors/couplings/templates/TimeSeries_HeatingIndirect/ConnectStatements.mopt
- geojson_modelica_translator/model_connectors/templates/EtsColdWaterStub_Instance.mopt
- geojson_modelica_translator/model_connectors/templates/EtsHotWaterStub_Instance.mopt
- geojson_modelica_translator/model_connectors/templates/HeatingIndirect_Instance.mopt
- geojson_modelica_translator/model_connectors/templates/NetworkChilledWaterStub_Instance.mopt
- geojson_modelica_translator/model_connectors/templates/NetworkHeatedWaterStub_Instance.mopt
Updated the heating indirect ETS parameters and BC " replaced the cooling with the heating".
@macintoshpie so far it is good, kindly merge my branch to feat/time-series-heating-indirect
> Time series heating indirect modifications

- geojson_modelica_translator/model_connectors/couplings/templates/HeatingIndirect_NetworkHeatedWaterStub/ComponentDefinitions.mopt
modified the district mass flow rate.
> Modified the district mass flow rate

- geojson_modelica_translator/model_connectors/couplings/templates/Network2Pipe_CoolingPlant/ConnectStatements.mopt
- geojson_modelica_translator/model_connectors/templates/CentralCoolingPlant.mot
- geojson_modelica_translator/model_connectors/templates/TimeSeriesBuildingNew.mot
modified templates of central cooling plant and building time series.
> Cooling district package

- README.rst
This PR incorporates a minor suggested correction to the instructions in the ReadMe on running simulations with JModelica, regarding where the jmodelica.py file is copied. Thanks, Nick! @nllong
> Read me update

- geojson_modelica_translator/model_connectors/templates/TimeSeries_Instance.mopt
Current ts building does not use sys params ts load filepath
Uses user-provided ts data
Run test_district_heating_and_cooling_systems.py
> refactor: remove ts instance filNam override

- geojson_modelica_translator/model_connectors/districts/templates/DistrictEnergySystem.mot
> add authorship.

- geojson_modelica_translator/model_connectors/load_connectors/templates/TeaserBuilding.mot
- geojson_modelica_translator/model_connectors/load_connectors/templates/TimeSeriesBuilding.mot
- geojson_modelica_translator/model_connectors/load_connectors/time_series.py
- Templatizes Teaser and time_series models
- Puts ETS template data into load_base.py, where it can be used by any of the models
`poetry run py.test`
This partially addresses #275
> Nate dehardcoding

- docs/getting_started.rst
> typo fixes

- tests/base_test_case.py
- tests/model_connectors/test_district_heating_and_cooling_systems.py
- tests/model_connectors/test_time_series_mft_ets.py
We haven't been checking the results of the simulations.
Check the results of the MFT model
* py.test
#303
> add values checking to mft test

- README.rst
- docs/developer_resources.rst
- docs/overview.rst
The load model documentation was lacking
Add more content to the load models in both the overview and the README.
n/a
#194
> cleanup the load model description

- docs/overview.rst
Ugh @nllong I wasn't clear in my comment earlier. My bad. And you've done the right thing to prevent me from commiting straight onto develop! 😆
> fix docs/overview.rst typo

- README.rst
@nllong Another tiny tiny thing I found. Literally added a period, that's it.
> Another tiny change

- tests/model_connectors/test_district_heating_and_cooling_systems.py
- tox.ini
Uses Load's QReq[Coo || Hea]_flow instead of ETS's Q_flow for thermal load assertion
na
#357
> test: update district H+C q flow assertions

- README.rst
- docs/getting_started.rst
Develop is `protected` so I can't commit straight to it, hence this PR.
> Complete docs for create-model in readme

- poetry.lock
I ran `poetry update` to resolve the PR's dependabot submitted.
Updates dependency versions for increased security
Addresses #438 #440
> ran `poetry update` to bump dependency versions

- geojson_modelica_translator/model_connectors/load_connectors/teaser.py
- geojson_modelica_translator/model_connectors/load_connectors/templates/TeaserCouplingBuilding.mot
Couple issues that need to be resolved before release.
* Fix the hard coding in the teaser load connector with thermalZoneFourElements
* Fix coupling file (not used in full disctrict models) to read only single heating and cooling supply.
* Fix coupling file's weather file raw/endraw tags
This really will be tested in the GMT-examples repo.
n/a
> Fix TEASER load model

- .github/workflows/ci.yml
- setup.cfg
> point tests to latest mbl release

- .github/workflows/ci.yml
- geojson_modelica_translator/modelica/lib/runner/README.md
- geojson_modelica_translator/modelica/lib/runner/docker-compose.yml
- geojson_modelica_translator/modelica/lib/runner/spawn_docker.sh
- geojson_modelica_translator/system_parameters/system_parameters.py
- poetry.lock
- pyproject.toml
- tests/model_connectors/test_district_heating_and_cooling_systems.py
- tests/modelica/test_modelica_runner.py
- tests/system_parameters/test_system_parameters.py
- tox.ini
* Add CI testing for compilation using the spawn_modelica_docker container
* Fix the logger I/O error (add in the `capture=no` into pypoetry.toml
* Use MBL 9.1 (this may need to be reversed)
> Run compilation tasks on CI using spawn Modelica and optimica

- geojson_modelica_translator/modelica/GMT_Lib/Electrical/AC/ThreePhasesBalanced/Lines/Lines.py
- geojson_modelica_translator/system_parameters/system_parameters.py
- poetry.lock
- tests/management/data/sdk_project_scraps/example_project.json
A Windows user reported problems with the CLI in the attached issue. This fixes that concern.
- Removes explicit casting to a float
- Adds a log entry
- Updates dependencies
- Makes mos weatherfile variable name more explicit
- Updates geojson file used in test to match the SDK
I'd like a human Windows user (not just our Windows CI) to confirm this passes:
`poetry run pytest tests/management/test_uo_des.py::CLIIntegrationTest::test_cli_builds_sys_params`
Resolves #503
> Cli bugfixing

- LICENSE.md
- geojson_modelica_translator/model_connectors/load_connectors/load_base.py
- geojson_modelica_translator/model_connectors/load_connectors/teaser.py
- geojson_modelica_translator/model_connectors/load_connectors/time_series.py
- geojson_modelica_translator/model_connectors/networks/__init__.py
Cleaning up the copyright and license language.
> Update license language

- .github/workflows/ci.yml
- geojson_modelica_translator/geojson/schemas.py
- geojson_modelica_translator/model_connectors/model_base.py
- geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX.py
- geojson_modelica_translator/modelica/input_parser.py
- geojson_modelica_translator/modelica/lib/runner/fmu_runner.py
- geojson_modelica_translator/modelica/lib/runner/spawn.py
- geojson_modelica_translator/modelica/modelica_runner.py
- geojson_modelica_translator/system_parameters/system_parameters.py
- mypy.ini
- pyproject.toml
- tests/base_test_case.py
Typing in 3.8 causes issues. We also used ast's Str type, which shouldn't have been used.
* install mypy into CI
* fix typing. This was specifically focused on supporting both Path and str. 
CI should suffice
> fix types on methods, bump to python 3.8

- geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX.py
- poetry.lock
- tests/GMT_Lib/test_gmt_lib_des.py
- tests/data_shared/B11.mos
A zero peak water heating load will not run correctly with MBL. 
* Zero out the water heating peak in one of the test files
* Ensures that some water heating load is always present
* Set to 1/10 of peak heating load, or 5,000W (whichever is larger)
* Run the `test_5G_des_waste_heat_and_ghx` method 
* Open the model in modelica
* Make sure it simulates
n/a
> Set SWH peak to 1/10th of space heating or min 5000W

- geojson_modelica_translator/modelica/lib/runner/om.py
- geojson_modelica_translator/modelica/lib/runner/simulate.most
- geojson_modelica_translator/modelica/modelica_runner.py
We were only using `stepSize` argument when running openmodelica,
* Add `number_of_intervals` as a simulation option. The simulation will favor `stepSize` if both are given.
* unit tests should suffice
n/a
> Enable numberOfIntervals run option

- .cspell/custom-dictionary-workspace.txt
- geojson_modelica_translator/model_connectors/districts/district.py
- geojson_modelica_translator/model_connectors/energy_transfer_systems/cooling_indirect.py
- geojson_modelica_translator/model_connectors/energy_transfer_systems/heating_indirect.py
- geojson_modelica_translator/model_connectors/load_connectors/spawn.py
- geojson_modelica_translator/model_connectors/load_connectors/teaser.py
- geojson_modelica_translator/model_connectors/load_connectors/time_series.py
- geojson_modelica_translator/model_connectors/load_connectors/time_series_mft_ets_coupling.py
- geojson_modelica_translator/model_connectors/plants/borefield.py
- geojson_modelica_translator/model_connectors/plants/chp.py
- geojson_modelica_translator/model_connectors/plants/cooling_plant.py
- geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_waste_heat_GHX.py
- geojson_modelica_translator/modelica/input_parser.py
- geojson_modelica_translator/modelica/package_parser.py
- geojson_modelica_translator/modelica/simple_gmt_base.py
- tests/GMT_Lib/test_gmt_lib.py
- tests/model_connectors/test_cooling_indirect.py
- tests/model_connectors/test_heating_indirect.py
- tests/model_connectors/test_teaser.py
- tests/model_connectors/test_time_series.py
- tests/modelica/test_package_parser.py
We had two classes in the input_parser file. That's not the best practice.
* Move PackageParser to its own file
* Add in spelling dictionary for use with VSCode's Spell Checker's extension
* Add typing info to PackageParser and InputParser
unit tests should suffice
n/a
> Breakout package parser class

- .github/workflows/ci.yml
- poetry.lock
Poetry often fails multiple times to install dependencies, especially (but I think not exclusively, IIRC) on Windows CI runs. I wanted to see if using a different GitHub Action to run Poetry would make a difference. I think it fails less often now, but definitely not zero failures 😢 .
The solution thus far is to re-run the failed jobs until they magically pass. I don't know why it works sometimes but not others.
Uses a different GitHub Action source for installing Poetry
Run CI and hope it passes all checks on the first try.
> test a new poetry gha

- .cspell.json
- CHANGELOG.rst
- pyproject.toml
> Prep for prerelease 0.6.0

- .github/ISSUE_TEMPLATE.md
- .github/release.yml
- management/data/baseline_sys_params.json
- poetry.lock
I want our helper files to be more helpful
- Remove ambiguity in issue dependency versions
- Now it will be clear if a user provided dependency versions when making an issue
- Update the data files used with the `check_sys_params` management task so it works with the current state of the GMT
- Exclude PRs with the `tests` label from automatic changelog generation by Github
- Update dependencies via Poetry
- Provide your opinion on the changes to the new issue template
- Try out the `check_sys_params` task, and ensure it works as expected
- Provide opinion on excluding PRs with the `test` label from the changelog
> Cleanup helpers

- geojson_modelica_translator/model_connectors/couplings/5G_templates/NetworkDistributionPump_Borefield/ConnectStatements.mopt
- geojson_modelica_translator/model_connectors/couplings/5G_templates/NetworkDistributionPump_NetworkDistributionPump/ComponentDefinitions.mopt
- geojson_modelica_translator/model_connectors/couplings/5G_templates/NetworkDistributionPump_NetworkDistributionPump/ConnectStatements.mopt
- geojson_modelica_translator/model_connectors/networks/templates/NetworkAmbientWaterStub_Instance.mopt
- geojson_modelica_translator/model_connectors/networks/templates/NetworkDistributionPump_Instance.mopt
- geojson_modelica_translator/model_connectors/plants/templates/BorefieldOneUTube.mot
- geojson_modelica_translator/model_connectors/plants/templates/BorefieldTwoUTubes.mot
- geojson_modelica_translator/model_connectors/plants/templates/GroundTemperatureResponse.mo
- tests/model_connectors/data/system_params_ghe.json
- tests/model_connectors/data/system_params_ghe_2.json
URBANopt GHP project
Change existing single GHE test to be closed-loop, which will overwrite the existing open-loop test
poetry run the test_single_ghe.py and then simulate the model in Dymola/OM
None
> Closed-loop changes to existing test_single_ghe test

- geojson_modelica_translator/modelica/GMT_Lib/DHC/DHC_5G_partial.mot
These variables were buried in the borFieDat within a borFie object.
Expose the parameters to make them easier to set.
Tests alone should suffice.
> Expose borehole variables

- CHANGELOG.md
- poetry.lock
- pyproject.toml
> Prep 0.6.1

- docs/getting_started.rst
Adjusting Docker resources is often required to simulate large Modelica models. This is trivial in Mac/Linux, and has multiple steps for Windows users that may not be immediately intuitive.
- Adds 2 links to documentation for setting resources on Windows machines
> Add detail to Docker setup docs for Windows users

- geojson_modelica_translator/system_parameters/schema.json
- geojson_modelica_translator/system_parameters/time_series_template.json
Unfortunately #640 was misguided and the COP values we are interested in are contained within the ETS for each building. Fortunately we already have those values populated in the template sys-param file.
Revert everything in #640 except the typo fixes
> Use the correct ETS heat pump COP

- .pre-commit-config.yaml
- geojson_modelica_translator/modelica/modelica_runner.py
- geojson_modelica_translator/system_parameters/system_parameters.py
- poetry.lock
- pyproject.toml
- tests/model_connectors/test_district_multi_ghe.py
Having a release candidate version published to PyPI makes it possible for UO-SDK to use this functionality natively
- Set an RC version for the GMT in pyproject.toml
- Update dependencies for the project with `poetry update`
- Update pre-commit hooks with `poetry run pre-commit autoupdate`
- Fix the pytest markers that I fiddled with on the multi-ghe test to make it easier for developers to not run that simulation accidentally
- Lint
Anything else we should do before sending a RC out into the wild?
> V0.8.0 rc1 prep

- tests/conftest.py
> Remove alfalfa from contest

- CHANGELOG.md
- pyproject.toml
Prepare for version 0.8.0
- Bump version in pyproject
- Update changelog
> V0.8.0 prep

- CHANGELOG.md
- poetry.lock
- pyproject.toml
New version with new MBL & new OM versions
- Bump version to v0.9.0
- update dependency versions
> Release v0.9.0

- .github/workflows/documentation_site.yml
- docs/docs_requirements.txt
- pyproject.toml
Still more mistakes/errors in my docs deployment setup
- Fix a typo in docs_requirements file
- Enable permissions for the workflow to write to gh-pages for us
> Release v0.9.1 rc2

- CHANGELOG.md
- pyproject.toml
Official patch release with bugs fixed
- https://github.com/urbanopt/geojson-modelica-translator/pull/684
- https://github.com/urbanopt/geojson-modelica-translator/pull/685
- New patch release to contain the correct docs link and improved docs deployment workflow
> Release v0.9.1

- geojson_modelica_translator/model_connectors/load_connectors/load_base.py
I had used a number of try/except blocks which was unnecessarily wordy. Cleaner!
- Replace some try/except blocks with dict.get()
- Remove an unnecessary `else: continue` from the if-statement
- Change print-statements to log items
> Clean up loadbase

- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
We can take advantage of new features & bug-fixes
- Updates Teaser to v1.1.0
- Updates pre-commit hook versions with `poetry run pre-commit autoupdate`
- Update dependencies with `poetry update`
> Update teaser to v1.1.0

- CHANGELOG.md
- pyproject.toml
> Prep v0.9.2

- .pre-commit-config.yaml
- README.md
> Cleanup Lingering RST Doc Extensions

- geojson_modelica_translator/model_connectors/energy_transfer_systems/templates/HeatPumpCooling.mot
- geojson_modelica_translator/model_connectors/energy_transfer_systems/templates/HeatPumpTrio.mot
- geojson_modelica_translator/model_connectors/load_connectors/load_base.py
- geojson_modelica_translator/model_connectors/load_connectors/templates/TimeSeriesBuilding.mot
- geojson_modelica_translator/model_connectors/load_connectors/templates/TimeSeriesBuildingWithETS.mot
- geojson_modelica_translator/model_connectors/load_connectors/templates/TimeSeries_Instance.mopt
- tests/model_connectors/data/system_params_ghe_2.json
This is the other piece of #710. Branch [new-ets](https://github.com/urbanopt/geojson-modelica-translator/tree/new-ets) associated with #710 was merged into this branch.
It edits 1) TimeSeriesBuildingWithETS.mot, 2) load_base.py, 3) TimeSeriesBuilding.mot, and 4) TimeSeries_Instance.mopt to use the ETS added in #710. Non essential changes to avoid an error in Modelica simulation in test_district_single_ghe.py were done in system_params_ghe_2.json 1) central_pump_parameters/pump_design_head, and 2) ghe_specific_params/borehole/number_of_boreholes
It can be manually tested by running test_district_single_ghe.py and test_district_multi_ghe.py and making sure they 1) have mechanical cooling within the ETS Modelica model, and 2) simulate in Modelica with no errors. In addition, making sure …
> Heat pump trio

- CHANGELOG.md
- pyproject.toml
Release new capabilities
Bump to version 0.10.0
> Release 0.10.0

- .pre-commit-config.yaml
- CHANGELOG.md
- pyproject.toml
Publish recent work:
- Waste heat districts
- Update borefield schema to enable using more of GHED design geometries
Release new features in a version to PyPI
> Prep 0.11.0
